### PR TITLE
Updated to Pixelmon 9.1.6

### PR DESCRIPTION
**Pull request by Nukecraft5419**

### CODE REVIEW

**Comment by danorris709** [comment]
This doesn't do anything other than reformat files and change the number - also 9.1.7 came out

**Comment by Nukecraft5419** [comment]
Yes, it's true that 9.1.7 came out and I wanted to try to make it compatible with 9.1.6, but it's the first time I've tried to do a porting if you could help me understand what I've done wrong

**Comment by danorris709** [comment]
This change doesn't make it compatable with 9.1.6 it simply changes the dependency number so that when writing the mod you can use the updated dependency. It was already compatable with 9.1.6 given you had to make 0 other changes

**Comment by Nukecraft5419** [comment]
I see, I hope to better understand how to do porting

**Pull request closed without merging**
